#! /bin/sh
#
# Determine the dependencies of a *.tex Tex/Latex source file.  Used by
# Jérôme Kunegis for compiling papers. 
#
# INVOCATION 
# 	$0 FILENAME
#
# STDOUT 
#	List of dependencies, one file per line
#
# ENVIRONMENT
#	$TEXDEP_GRAPHICSEXT	(optional) extension of included graphics,
#				without the dot; defaults to "pdf"
#
# ABOUT
#	(c) 2015, 2016 Written by Jérôme Kunegis <kunegis@gmail.com>
#

file="$1"

[ "$file" ] || {
	echo >&2 '*** Missing filename'
	echo >&2 "Invocation:  $0  FILENAME"
	exit 1
}

if [ -z "$TEXDEP_GRAPHICSEXT" ] ; then
	graphicsext=pdf
else
	graphicsext="$TEXDEP_GRAPHICSEXT"
fi

#
# The file itself
#

echo "$file"

#
# Bibtex source files
#

<"$file" sed -e '
/\\bibliography{/!d
s,^[^{]*{\([^}]*\).*$,\1,
' | tr ',' '
' |
sed -e 's,$,.bib,'

#
# Bibliography style file
#

<"$file" sed -E -e '
s,^.*\\bibliographystyle\{(.+)\}.*$,\1.bst,
t;d
' | while IFS= read -r filename ; do
	[ -e "$filename" ] && echo "$filename"
done

#
# Plots
#

<"$file" sed -E -e '
/^\s*%/d
s,^.*(\\includegraphics|\\begin\{overpic\})[^{]*\{([^}]+)\}.*$,\2,
t;d
' |
while IFS= read name ; do

	# Empty name
	if [ -z "$name" ] ; then
		continue
	fi

	# Add extension only if there is not already one
	if echo "$name" | grep -qvE '\.(pdf|png|eps|jpg)$' ; then
		name="$name.$graphicsext"
	fi

	echo "$name"
done

#
# Other included .tex files
#

<"$file" sed -E -e '
s,^[^%]*\\input.*\{([^}]+)\}.*$,\1,;t;d
#/\\input.*\{/!d;s,^.*\{,,;s,\}.*$,,
' |
while IFS= read -r name ; do
	if [ -z "$name" ] ; then
		continue
	fi
	if echo "$name" | grep -qvE '\.tex$' ; then
		name="$name.tex"
	fi
	echo "$name"
done

#
# CLS files
#

<"$file" sed -E -e '/\\documentclass\{/!d;s,^.*\\documentclass\{(.*)\}.*$,\1,;/article/d' |
while IFS= read -r name ; do
	echo "$name.cls"
done

